version: '3'
services:
  db:
    container_name: shiori-db
    image: mysql:8.0.20
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3316:3306'
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql:delegated
      - ./db/mysql/mysql-conf.d:/etc/mysql/my.cnf

  app:
    container_name: shiori-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /bin/bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: .env
    volumes:
      - .:/shiori:delegated
      - bundle:/usr/local/bundle:delegated
    ports:
      - "3000:3000"
    depends_on:
      - db

  esbuild:
    container_name: esbuild
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /bin/bash -c "yarn build --watch"
    tty: true
    env_file: .env
    volumes:
      - .:/shiori:delegated

  cssbuild:
    container_name: cssbuild
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /bin/bash -c "yarn build:css --watch"
    tty: true
    env_file: .env
    volumes:
      - .:/shiori:delegated

volumes:
  bundle:
