version: '3'
services:
  db:
    container_name: shiori-db
    image: postgres:13.5
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - '5432:5432'
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data:delegated
    user: root

  app:
    container_name: shiori-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /bin/bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: .env
    volumes:
      - .:/shiori:delegated
      - bundle:/usr/local/bundle:delegated
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  bundle:
