default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: db

development:
  <<: *default
  database: shiori_development

test:
  <<: *default
  database: shiori_test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
